### ISSUE TITLE
上に戻るボタンを導入

### ISSUE THREAD

**Issue by megane9988** [megane9988/gridsome-megane-blog#10]

**Comment by megane9988** [comment]
そのままではNetlifyのビルドのときにerrorになる

```
2:09:37 PM: ReferenceError: window is not defined
2:09:37 PM:     at Object.<anonymous> (node_modules/@inotom/vue-go-top/dist/vue-go-top.umd.js:2:198)
2:09:37 PM:     at __webpack_require__ (webpack/bootstrap:25:0)
2:09:37 PM:     at Module.<anonymous> (assets/js/app.7031a852.js:11382:22)
2:09:37 PM:     at __webpack_require__ (webpack/bootstrap:25:0)
2:09:37 PM:     at Object.<anonymous> (assets/js/app.7031a852.js:4222:18)
2:09:37 PM:     at __webpack_require__ (webpack/bootstrap:25:0)
2:09:37 PM:     at assets/js/app.7031a852.js:118:18
2:09:37 PM:     at Object.<anonymous> (assets/js/app.7031a852.js:121:10)
2:09:37 PM:     at o (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:77545)
2:09:37 PM:     at /opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:78138
```

どうやら、ブラウザでないのでwindowが無いのが問題らしい
んで、解決策も幾つか出てくる

https://mebee.info/2020/02/17/post-5983/

そしてたどり着いたissueがこちら

https://github.com/gridsome/gridsome/issues/180

Githubで議論があるの本当に助かる

**Comment by megane9988** [comment]
結局このerrorに対応できなくて、仕方なく
https://www.npmjs.com/package/vue-scrollto
を利用

一番外枠の要素に`#top` いれてたけど、こちらでは動かなくて
ロゴ部分に入れる。
とりあえず動いたので良しとする
